name = "ice-calendar-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV storage for calendar events
[[kv_namespaces]]
binding = "CALENDAR_EVENTS"
id = "your-kv-namespace-id"  # Replace with your actual KV namespace ID
preview_id = "your-preview-kv-namespace-id"  # Replace with your preview KV namespace ID

# Environment variables
[vars]
CALENDAR_NAME = "Ice Calendar"
CALENDAR_DESCRIPTION = "Calendar populated from email forwards"

# Email routing configuration
[[email]]
name = "calendar-email"
destination_address = "calendar@yourdomain.com"  # Replace with your email