name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30
