# This workflow automatically merges Dependabot PRs for minor and patch updates.
# Major version updates require manual review for safety.
# 
# Requirements:
# 1. Enable "Allow auto-merge" in repository settings
# 2. Configure branch protection rules with required status checks (optional)

name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      # Enable auto-merge for minor and patch updates only
      - name: Enable auto-merge for minor and patch updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Add labels for better PR organization
      - name: Label PR by update type
        run: |
          case "${{ steps.metadata.outputs.update-type }}" in
            "version-update:semver-major")
              gh pr edit "$PR_URL" --add-label "dependencies,major-update"
              ;;
            "version-update:semver-minor")
              gh pr edit "$PR_URL" --add-label "dependencies,minor-update"
              ;;
            "version-update:semver-patch")
              gh pr edit "$PR_URL" --add-label "dependencies,patch-update"
              ;;
          esac
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Note: GitHub's auto-merge feature will automatically wait for all required status checks
      # to pass before merging. Major updates will not be auto-merged and require manual review.
