name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run-ci:
    name: Run CI
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/ci.yml

  deploy-from-ci:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (from CI)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [run-ci]
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (manual)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
