name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-ci:
    name: Run CI
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/ci.yml

  deploy-from-ci:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (from CI)
    steps:
      - uses: ./.github/actions/deploy

  deploy-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [run-ci]
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers (manual)
    steps:
      - uses: ./.github/actions/deploy
